export default {
  STATE: "State",
  UT: "Union Territory",
  DISTRICT: "District",
  CONFIRMED: "Confirmed",
  ACTIVE: "Active",
  RECOVERED: "Recovered",
  DEATHS: "Deaths",
  DECEASED: "Deceased",
  NATIONALCOUNT: "TT",
  ZONES: "Zones",
  RECOVERY_RATE: "Recovery Rate",
  DEATH_RATE: "Death Rate",
  AS_ON: "All Figures as on: ",
  TIME_NOW: "Time now: ",
  NA: "N/A",
  ERROR_HEADING: "Oops! There was an error.",
  ERROR_MESSAGE:
    "Check your internet connection and try again. If the issue persists, contact the site owner.",
  SIKKIM: "Sikkim",
  SIKKIM_CODE: "SK",
  API_HOME_PAGE_LINK: "https://api.covid19india.org/",
  DATASOURCE: "DATASOURCE (Crowd-Sourced Database)",
  ABOUT: "About",
  GITHUB_REPO_LINK: "https://github.com/mehulsengupta/covid19indiastatus",
  GITHUB_REPO: "Github",
  EMAIL_ME: "mehulsengupta20@gmail.com",
  CONTACT: "Contact",
};
