export default {
  STATE: "State",
  UT: "Union Territory",
  DISTRICT: "District",
  CONFIRMED: "Confirmed",
  ACTIVE: "Active",
  RECOVERED: "Recovered",
  DEATHS: "Deaths",
  DECEASED: "Deceased",
  NATIONALCOUNT: "TT",
  ZONES: "Zones",
  RECOVERY_RATE: "Recovery Rate",
  DEATH_RATE: "Death Rate",
  AS_ON: "All Figures as on: ",
  TIME_NOW: "Time now: ",
  NA: "--",
  HOURGLASS_ICON: "fa fa-hourglass-half",
  ERROR_HEADING: "Oops! There was an error.",
  ERROR_MESSAGE:
    "Check your internet connection and try again. If the issue persists, contact the site owner.",
  SIKKIM: "Sikkim",
  SIKKIM_CODE: "SK",
  STATE_UNASSIGNED: "UN",
  API_HOME_PAGE_LINK: "https://api.covid19india.org/",
  DATASOURCE: "Crowd-Sourced Database",
  ABOUT: "About",
  GITHUB_REPO_LINK: "https://github.com/mehulsengupta/covid19indiastatus",
  GITHUB_REPO: "GitHub",
  EMAIL_ME: "mehulsengupta20@gmail.com",
  CONTACT: "Contact",
  FAQ: "FAQs on COVID19",
  FAQ_LINK: "https://www.mohfw.gov.in/pdf/FAQ.pdf",
  PREVENTION: "Protective Measures",
  PREVENTION_LINK: "https://www.mohfw.gov.in/pdf/ProtectivemeasuresEng.pdf",
  SYMPTOMS: "Symptoms",
  SYMPTOMS_LINK:
    "https://www.cdc.gov/coronavirus/2019-ncov/symptoms-testing/symptoms.html",
  GOVT_CONTACT_HDR: "Government of India helplines: ",
  GOVT_CONTACT_TF: "1075",
  GOVT_CALL_LL_LINK: "+911123978046",
  GOVT_CONTACT_LL: "011-23978046",
  INITIAL_LOADER: "TailSpin",
  INITIAL_LOAD_TIME: "1000",
  COMPONENT_LOADER: "ThreeDots",
  COMPONENT_LOAD_TIME: "0",
  DEFAULT_LOADER: "ThreeDots",
  LOADER_COLOR: "blue",
  FADE_IN_COMPONENT_DELAY: 300,
  FADE_IN_TRANSITION_DURATION: 1000,
};
